### ISSUE TITLE
Adding enforced format.xml

### ISSUE THREAD

**Issue by hazendaz** [mybatis/guice#102]
@christianpoitras I've been adding to the various projects format.xml which is in mybatis-parent now.  This enforces 2 character spacing for mybatis.  This has been an easy win for smaller projects at this point.  I was thinking about possibly bringing it in here given checkstyle complaints over 3k.  It won't fix all those issues but will knock off a good number.  Because this is such a noisy change in general the first time, I wanted to raise the question here letting you decide if it is worth doing.  There are no outstanding PR so if anytime was a good time, now is.

**Comment by christianpoitras** [comment]
I agree to check and fix all complains that make sense.

**Comment by christianpoitras** [comment]
I'll try to look at this later this week. I also plan to finally add all those missing unit tests.

**Comment by hazendaz** [comment]
Fixed via #103
