### ISSUE TITLE
Configuration Variables

### ISSUE THREAD

**Issue by lflobo** [mybatis/guice#12]
Currently there is no way of changing variables in the default Configuration (org.apache.ibatis.session.Configuration) generated by mybatis-guice.

If you want to use variables assigned to the current Configuration in the mapper files (xml), you need to call config.getVariables().put() before the mapper xml files are parsed.

With the current mybatis-guice layout you can't.

I'm using:
mybatis-guice-3.3

**Comment by christianpoitras** [comment]
Closing since it seems like a question and we didn't receive an update in over a year.
