### ISSUE TITLE
Drop bonecp support

### ISSUE THREAD

**Issue by hazendaz** [mybatis/guice#139]
@christianpoitras WDYT?

**Comment by christianpoitras** [comment]
I don't know if anyone is using it. It seems to have been added a long time ago when I was not a developper for the plugin. I don't think I ever updated that part and it may be very outdated.
So I don't have a strong opinion on this one.

**Comment by christianpoitras** [comment]
Based on Maven, the last update to BoneCP was in 2013. It is likely that the project is dead.

**Comment by christianpoitras** [comment]
@hazendaz  I agree to get rid of BoneCP support.

**Comment by hazendaz** [comment]
bonecp test is skipped as it breaks jdk 11 usage.
