### ISSUE TITLE
Add support for HikariCP (as suggested replacement for bonecp)

### ISSUE THREAD

**Issue by hazendaz** [mybatis/guice#141]

**Comment by robotdan** [comment]
I am using HikariCP w/ Mybatis, no issues that I know. 

- mybatis 3.4.6
- mybatis-guice 3.10
- Hikari 2.6.1

**Comment by hazendaz** [comment]
Hi, @robotdan, Thanks for confirming it does work.  What is missing is direct integration though as found in this [package](https://github.com/mybatis/guice/tree/master/src/main/java/org/mybatis/guice/datasource).  If possible maybe you could build and submit a pull request that would provide native support as with other datasources?  I'm not super familar in this are of code and only noted this needed done after reviewing current support and libaries that are no longer supported.

**Comment by robotdan** [comment]
@hazendaz Sure, I'll see if I can boil something down and put together a PR.

**Comment by christianpoitras** [comment]
@robotdan Thanks! I am quite busy and it is faster to review a PR than to program this myself. So it would be very appreciated. :)

**Comment by robotdan** [comment]
FYI, I haven't forgotten about this. I have it mostly coded, just finishing the tests. If anyone is in a hurry for it I can push my fork before I submit a PR.

**Comment by christianpoitras** [comment]
Thanks @robotdan !

I will not have time to review your changes before next week, so no hurry.

**Comment by gibsonm** [comment]
Did a version of HikariCP datasource provider get pushed anywhere we can grab it from?

**Comment by christianpoitras** [comment]
Not yet. I was waiting for @robotdan in case he had a PR ready.

**Comment by robotdan** [comment]
Sorry for the delay, you know how it goes. 😁 I do have a PR mostly ready. I'll try to put it together in the next day or two.

**Comment by gibsonm** [comment]
:) Feel free to fork early if you think you'll be delayed in the PR.  And thanks for your efforts.

**Comment by robotdan** [comment]
Submitted PR https://github.com/mybatis/guice/pull/168 - may still need some work. I'm happy to continue to contribute to it if you need anything. We have been using MyBatis + HikariCP for ~ 5 years.

**Comment by gibsonm** [comment]
Thank you @robotdan .  Pretty much what I was expecting.  I'll take it for a spin locally whilst waiting for the PR to propagate through to release.

**Comment by robotdan** [comment]
@gibsonm  You're welcome, let me know if I can help with anything else.

**Comment by christianpoitras** [comment]
Fixed with PR #168
