### ISSUE TITLE
Transactional annotation doesn't work in Kotlin

### ISSUE THREAD

**Issue by maxim432** [mybatis/guice#194]
`@Transactional` on Kotlin methods seems to be ignored, and every statement in the method shows up as an independent transaction in SQL log, instead of all within one transaction.

The same code in Java works as expected, which makes me believe it is something about Kotlin.

Is Kotlin supported, and if not are there plans for it?

Tested with
Kotlin 1.3.0
mybatis:3.5.4
mybatis-guice:3.12
guice:4.2.3

Update: the root cause is that Kotlin classes and methods are final by default, which [breaks guice bindInterceptor](https://github.com/misfitlabsdev/kotlin-guice/issues/11) that is used to register `@Transactional` annotation. A workaround is making the annotated method and its containing class `open`.

**Comment by christianpoitras** [comment]
I don't know Kotlin. But if the methods are final, Guice cannot intercept them.
Your reference is right and explains the problem correctly.

**Comment by christianpoitras** [comment]
I will close the issue since it is not related to MyBatis-Guice.
