### ISSUE TITLE
Support for registering new languages and setDefaultScriptingLanguage

### ISSUE THREAD

**Issue by natros** [mybatis/guice#25]
Support for registering new languages and setDefaultScriptingLanguage

**Comment by christianpoitras** [comment]
Using MyBatis 3.2.8, language drivers with ```@Inject``` cannot be registered.

I filed an issue in MyBatis for this. https://github.com/mybatis/mybatis-3/issues/342

**Comment by christianpoitras** [comment]
I think I'll close the issue since language driver can be registered from a mapper using the ```@Lang``` annotation and I don't see how these language drivers can have their dependencies injected.
