### ISSUE TITLE
Add Tx Transaction interceptor

### ISSUE THREAD

**Issue by alexey-su** [mybatis/guice#29]
In a local version of the project, I added support for JTA TransactionManager.

Borrowed the description of the rules of the transaction JavaEE 7 
	javax.transaction.Transactional.TxType.
My main project is working on the JVM 1.6. In Java 6 no @Transactional.

Took two objects from the project Apache Aries transaction-jdbc.
* TransactionToken 
* TransactionAttribute.

To work with TransactionManager must register this object

```java
TransactionManager manager;

install(new MyBatisModule(){
	@Override
	protected void initialize() {
		if(manager != null)
			bind(TransactionManager.class).toInstance(manager);
	}
});
```
Transactional annotation processing consistently put two handlers.
The first handler TxTransactionalMethodInterceptor.
The second handler TransactionalMethodInterceptor.

TxTransactionalMethodInterceptor receives main object Guice
```java
@Inject Injector injector;
```

Requests the presence of a registered provider object TransactionManager.
If the object is not registered, transfers control parameter invocation.
If the object is registered
* The objects are mapped TxType it TransactionAttribute.
* Start process of initiating a transaction.
* Transfer control parameter invocation.
* If an error signal TransactionManager set rollbackOnly.
* Ends the transaction (commit or rollback).

Change: https://gist.github.com/alexey-su/567495a9d29b0d175b7c

**Comment by christianpoitras** [comment]
Hi,
Adding support for JTA is a nice idea. Do you have any unit tests to check that everything works?

**Comment by emacarron** [comment]
In case it is of any help, you can have a look at CDI [1]. We coded a basic
JTA support and some unit tests that can probably be reused for Guice.

[1] https://github.com/mybatis/cdi

2015-01-29 15:12 GMT+01:00 Christian Poitras <notifications@github.com>:

**Comment by christianpoitras** [comment]
Nice! I saw that MyBatis-CDI had a Transactional annotation, but I'm glad they support JTA because they are often used together.

**Comment by alexey-su** [comment]
Honestly, I did not write the tests. I look forward correction mistakes https://issues.apache.org/jira/browse/ARIES-1279.
January 20 was amended draft Aries (ARIES-1287). Hopefully be able to check the error ARIES-1279.

I changed my little project. Create a new component
MyBatisJtaModule extends MyBatisModule

Added method bindTransactionInterceptors() and redefined in the new class.
In this way, I thought to myself the trouble of using IdempotentRepository in Apache Camel.
Appeal to the data store goes beyond the basic transaction Camel Route.

CDI implementation works only with the current transaction. I use TransactionManager
to create a new transaction REQUIRES_NEW and other options.
In the beginning I used UserTransaction. But encountered an error. Close the current transaction and should open a new transaction.
UserTransaction component returns a status other than Status.STATUS_NO_TRANSACTION.
At the same time, UserTransaction correctly gives the status Status.STATUS_NO_TRANSACTION.

Change: https://gist.github.com/alexey-su/d1b05460c7fc59aab60e

**Comment by alexey-su** [comment]
Added a lot of tests for JTA. Had to tinker.
https://gist.github.com/alexey-su/b9232686bf98aaca2619

I hope you enjoy.

**Comment by emacarron** [comment]
We will!!! Thank you Alexey. Hope I can have a look at it this weekend.

2015-02-08 23:41 GMT+01:00 alexey-su <notifications@github.com>:

**Comment by christianpoitras** [comment]
@emacarron You can steal the issue from me if you have time! ;)

**Comment by christianpoitras** [comment]
Oups... I though I assigned it to myself...

**Comment by christianpoitras** [comment]
Hi, I checked the code and it seems nice and well done. The only thing I don't like is the compile dependency on geronimo. Is that really required? Or can it be made optional for those that don't use JTA?

I didn't test it in a actual JTA environment, but I'll believe you if you say it works.

**Comment by christianpoitras** [comment]
I removed the NamedXAResource from the implementations of XASqlSessionManager and set geronimo dependency as test and all works well.

@alexey-su Is that an option to make geronimo optional for non-JTA users?

**Comment by natros** [comment]
Can't you use <optional>true</optional> in the <dependency>. 

"optional=true means that a library is needed for compilation, but it is not necessary at runtime"

**Comment by alexey-su** [comment]
I chose Geronimo only for tests. My projects are working on Apache Karaf + Apache Camel.
This implementation TransactionManager used in this bundle.

In the realization of Geronimo TransactionManager have unpleasant moment. He does not use a standard interface
NamedXAResource. This interface is needed for the transaction log records in the file.
Evident when working with multiple physical databases (different servers).
I do not like it. We need to think about the possibility to override XASqlSessionManager.
And in a new class implement the interface NamedXAResource.

The ugliest in this implementation - an object XASqlSessionManager.
He climbs through introspection to a private object field SqlSessionManager.

In the manifest file "optional = true". This is for OSGi. Not necessarily to use at runtime.

**Comment by alexey-su** [comment]
I chose Geronimo only for tests. My projects are working on Apache Karaf + Apache Camel.
This implementation TransactionManager used in this bundle.

In the realization of Geronimo TransactionManager have unpleasant moment. He use  interface NamedXAResource. This interface is needed for the transaction log records in the file.
Evident when working with multiple physical databases (different servers).
I do not like it. We need to think about the possibility to override XASqlSessionManager.
And in a new class implement the interface NamedXAResource.

```
java.lang.IllegalStateException: Cannot log transactions as org.mybatis.guice.transactional.XASqlSessionManager@aa7781d is not a NamedXAResour
        at org.apache.geronimo.transaction.manager.TransactionImpl$TransactionBranch.getResourceName(TransactionImpl.java:776)
        at org.apache.aries.transaction.internal.HOWLLog.prepare(HOWLLog.java:262)
        at org.apache.geronimo.transaction.manager.TransactionImpl.internalPrepare(TransactionImpl.java:467)
        at org.apache.geronimo.transaction.manager.TransactionImpl.commit(TransactionImpl.java:312)
```

The ugliest in this implementation - an object XASqlSessionManager.
It uses introspection to access to a private field SqlSessionManager.
```
Field field = SqlSessionManager.class.getDeclaredField("localSqlSession");
field.setAccessible(true);
```
In the manifest file "javax.transaction.*;resolution:=optional". This is for OSGi. Not necessarily to use at runtime.

**Comment by christianpoitras** [comment]
How about having a provider for XASqlSessionManager? Users could choose their implementation and we can make Geronimo dependency optional.

https://github.com/christianpoitras/guice/tree/xasessionmanager

**Comment by christianpoitras** [comment]
In a patch format. https://gist.github.com/christianpoitras/34b38a0328b9a6114d4d#file-custom_xasessionmanager

**Comment by alexey-su** [comment]
The most basic thing - it is to pass a parameter SqlSessionManager to constructor XASqlSessionManager.
Further, all work on this object is as to the implementation of the interface XAResource.

We do not think about implementation of the interface when working with the database.
```
XAConnection con;
XAResourec xar = con.getXAResource();
```
Here in the same way.
```
@Provider XASqlSessionManagerProvider provider;
XAResourec xar = provider.get();
```
I would not focus on the implementation of the interface Geronimo NamedXAResource.
Near NamedXAResource can detect class WrapperNamedXAResource.
Enough to get some interface implementation XAResourec and put in a constructor WrapperNamedXAResource.
```
public class NamedXASqlSessionManagerProvider extends XASqlSessionManagerProvider {

    public XAResource get() {
    	XAResource xaResource = super.get();
    	String name = ((XASqlSessionManager) xaResource).getId();
        return new WrapperNamedXAResource(xaResource, name);
    }	
}
```
Something like this is implemented wrapper RecoverableDataSource in libraries geronimo-connector.
RecoverableDataSource object used in the tests for a transparent connection to the JTA transactions.

**Comment by christianpoitras** [comment]
Here is a new version based on your comment. I like your idea of having a provider for XAResource rather than XASqlSessionManager!

https://gist.github.com/christianpoitras/34b38a0328b9a6114d4d

**Comment by alexey-su** [comment]
A very nice solution. I'm not very good at Guice. Share his concerns.

I think after the call initialize() should be put.
In AbstractMyBatisModule
```
void configure() {
    ...
    bindTransactionInterceptors();

    internalConfigure();

    bind(XAResource.class).toProvider(xaSqlSessionManagerProvider); // ???
    ...
}
```
If you leave the old order, the method call will not give the desired effect.
We tied the old object, and then changed the pointer to the new object.

There is a problem. Methods configure() and internalConfigure() are declared as final.

**Comment by christianpoitras** [comment]
You are right. I added a unit test to confirm that a custom provider can be used.

See https://gist.github.com/christianpoitras/34b38a0328b9a6114d4d

I'll remove the geronimo related provider and create a pull request.

**Comment by alexey-su** [comment]
I like your decision. I would like to see our work in the new version of the project.

I have an idea for future development. Support annotations transactions can be done at the level of MyBatis, and not at the level of Guice/Spring/CDI and other libraries. In SqlSessionManager add a method getXAResource().

**Comment by christianpoitras** [comment]
I'll send the comment to Eduardo to see his opinion on adding a getXAResource() method to SqlSessionManager.

We also need to add documentation for the new feature. I'll probably write one in the next few months.

**Comment by alexey-su** [comment]
I tried to show in tests actions within the transaction.
It is difficult to write documentation. I speak Russian.

The control system for the states in XASqlSessionManager taken from Bitronix LrcXAResource.
If you're interested, you can find on the forum Apache Camel. See attach source from http://camel.465427.n5.nabble.com/OSGi-JTA-and-NonXA-DataSource-td5626400.html

I'll be grateful to you for writing documentation.

**Comment by christianpoitras** [comment]
Merged https://github.com/mybatis/guice/pull/38.

**Comment by christianpoitras** [comment]
@alexey-su Is a XA DataSource required to use MyBatisJTAModule? Or can JTA use a non-XA DataSource inside a XAResource instance?

**Comment by alexey-su** [comment]
No dependence on XADataSource. Using the add-on XADataSource.
The basic functionality of the session MyBatis only works with DataSource.

Example of creating a non-XA can be found here: https://developer.jboss.org/thread/169430?tstart=0
In tests, I used the implementation tranql-connector and org.apache.aries.transaction.jdbc.
It was easier to raise *RecoverableDataSource*, rather than understand the *ManagedDataSource* picked up by dbcp.

It would be all very nice if the code looks the same as the documentation for the Apache DeltaSpike JPA module.
I have not analyzed the implementation of this module. Maybe we can do something similar for MyBatis.

**Comment by christianpoitras** [comment]
@alexey-su Hi! Is there any requirement to use the MyBatisJTAModule? For example is a TransactionManager required?
If so I will add this to the documentation.

Thanks again! The documentation is almost done since there was not much to say.

**Comment by alexey-su** [comment]
Yes, MyBatisJTAModule use interface TransactionManager.

JavaEE 6 EJB component:

```java
@Resource TransactionManager tm;  // JavaEE 6
```

Or JavaEE 7 bean:

```java
@Inject TransactionManager tm;  // JavaEE 7 or CDI
```

Or OSGi service from ServiceReference:

```java
BundleContent bundleContent;
ServiceReference<TransactionManager> reference = 
  bundleContent.getServiceReference(TransactionManager.class);
TransactionManager tm = bundleContent.getService(reference);
```

Or OSGi service from OSGi Enterprise Editon use lookup:

```java
InitialContext initCtx = new InitialContext();
   String txName = "osgi:service/javax.transaction.TransactionManager"
   TransactionManager tm = (TransactionManager) initCtx.lookup(txName);
```

or OSGi Dynamic Service SCR annotation:

```java
@Component
@References({
  @Reference(
    name                = "transactionManager",
    referenceInterface  = TransactionManager.class,
    cardinality         = ReferenceCardinality.MANDATORY_UNARY,
    policy              = ReferencePolicy.STATIC,
    bind                = "bindTransactionManager",
    unbind              = "unbindTransactionManager"),
})
public MyComponent {
  TransactionManager tm;

  bindTransactionManager(TransactionManager tm) {
    this.th = tm;
  }

  unbindTransactionManager(TransactionManager tm) {
    this.tm = null;
  }
}
```

Further, it is necessary to create an object for the add database JTA Transaction.
This can be Apache DBCP ManagedDataSource or Apache Aries RecoverableDataSource.
In JBoss or WildFly it's component from standalone.xml file

```xml
<datasource jta="true" jndi-name="java:/MyDataSource" ...> ... </datasource>
```

Do not be confused by JavaEE 6 annotation @javax.ejb.TransactionAttribute 
or JavaEE 7 annotation @javax.transaction.Transactional.
Even the presence of a transaction in Camel route

```java
from("seda:mywork")
.transacted("required")
.to(myProcess);
```

Handler transactions properly fit into an active JTA UserTransaction.

**Comment by alexey-su** [comment]
Others do not have explicit dependencies.
It uses its own implementation of XAResource to SqlSessionManager.
Our annotations processor registers XAResource in the transaction.

It is likely a situation where one method with annotation @org.mybatis.guice.transactional.Transactional can be called from another method with the same annotation.
Each handler creates and registers a new resource XAResource. Within a single transaction resource monitors used SqlSession. If the session has already been involved in a transaction, use this session. If the transaction is not involved session, opens a new session, and the old session is stored until the completion of the transaction.

**Comment by christianpoitras** [comment]
Thanks for the example on how to get the TransactionManager!

Since users need to supply a TransactionManager to the JTAMyBatisModule I will add this to the documentation.

The good news is that if users use Java EE, then they can get an instance of TransactionManager and a managed data source easily.

**Comment by christianpoitras** [comment]
@alexey-su Here is the documentation that I wrote for the JTA support.
https://dl.dropboxusercontent.com/u/26970733/mybatis-guice/jta.html

I this acurate? Do you think I should add anything?

Thanks again!

**Comment by alexey-su** [comment]
I like that. For the start-up phase will be fine. People will start to work and be able to suggest changes in the description.

When a bunch of Guice and JavaEE must be very careful.
Weld and Guice implement the same processing annotations.

As an example of JavaEE 7 CDI
```java
@Servlet("/path")
public class MyRestBean {
  @Inject TransactionMamager tm;
}
```
MyBatisJtaModule registers field TransactionMamager.
```java
bind(TransactionManager.class).toInstance(manager);
```
When you work at the intersection of the two systems, the main thing is not to get confused which system is responsible for what.

**Comment by christianpoitras** [comment]
Documentation added in commit 197d0295fd286f3220b591855e87d74a2011ffe1.

**Comment by christianpoitras** [comment]
Thanks for your help!
As you say, the documentation will most likely change in the future after we get some feedback from the uses. At least they will have a starting point to use it. And I will answer questions on the mailing list.
