### ISSUE TITLE
Set custom driver property

### ISSUE THREAD

**Issue by lchaubert** [mybatis/guice#33]
Hello,

I need to set a driver property using Names.bindProperties(binder(), properties);
The JDBC connection property is settable in JDBC with properties.setProperty("foreign_keys", "true"); but I didn't manage to do it with MyBatis. Can you please explain me how can I do it?

Thy in advance!

Lucien

**Comment by christianpoitras** [comment]
Hi, please ask your question on the mailing list.
http://mybatis.github.io/mybatis-3/mail-lists.html

As an hint, your JDBC connection properties should start with "JDBC.". See http://mybatis.github.io/guice/getting-started.html

**Comment by lchaubert** [comment]
Sorry for posting at the wrong place.

I eventually figured out how to pass driver properties to the datasource using:

bind(Properties.class).annotatedWith(Names.named("JDBC.driverProperties")).toInstance(driverProperties);

All the best,

Lucien
