### ISSUE TITLE
SampleBasicTest not work in Java 1.8

### ISSUE THREAD

**Issue by alexey-su** [mybatis/guice#35]
The last test (shouldNotFailOnObjectsMethodsCall) does not work with Java 1.8

**Comment by christianpoitras** [comment]
Which version of Java 1.8 is failing exactly?

I tried Java 1.8.0, 1.8.0_05 and 1.8.0_25 (all 64 bits) on Windows and all tests succeed.

**Comment by alexey-su** [comment]
I checked again. The error is not repeated.

java version "1.8.0_40"
Java (TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot (TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

Please close this bug.
