### ISSUE TITLE
Setting Configuration properties not directly supported by ConfigurationProvider?

### ISSUE THREAD

**Issue by george-hawkins-aa** [mybatis/guice#42]
The `Configuration` instance is created in `org.mybatis.guice.configuration.ConfigurationProvider.get()`.

In this method the various named properties found at the top of the class are used to setup the `Configuration` instance.
                                                                                                
These properties only cover a subset of those supported by `Configuration`, `setDefaultStatementTimeout(Integer)` and various others are not covered.
                                                                                                
And the current ordering of things means there's no opportunity to modify the `Configuration` instance before the mapped statements are built.

E.g. here we can see `getDefaultStatementTimeout()` is called as part of creating the mapped statement (see top of stack) and this is triggered as part of creating the `Configuration` (see bottom of stack):
                                                                                                                                                                       
    Configuration.getDefaultStatementTimeout()
    MappedStatement$Builder.<init>(Configuration, ...
    MapperBuilderAssistant.addMappedStatement(...
    XMLStatementBuilder.parseStatementNode()
    XMLMapperBuilder.buildStatementFromContext(List<XNode>, String)
    XMLMapperBuilder.buildStatementFromContext(List<XNode>)
    XMLMapperBuilder.configurationElement(XNode)
    XMLMapperBuilder.parse()
    MapperAnnotationBuilder.loadXmlResource()
    MapperAnnotationBuilder.parse()
    MapperRegistry.addMapper(Class<T>)
    Configuration.addMapper(Class<T>)
    ConfigurationProvider.get()
    ConfigurationProvider.get()
    BoundProviderFactory<T>(ProviderInternalFactory<T>).provision(...

So there's no possibility to set things like the default statement timeout inbetween the creation of the `Configuration` and their use in creating mapped statements.

At the moment it looks like the only solution to setting unsupported properties is to generate a pull request (involving a new named property in `ConfigurationProvider`) and then wait for a new release.

Is this correct?

**Comment by christianpoitras** [comment]
I think you are right. If you have a better alternative, I'll be happy to have a look at it.

**Comment by christianpoitras** [comment]
The pull request #60 offers an alternative for now.

The only other option I can think of is to use reflection or to supervise all changes in MyBatis and to try to keep the Guice plugin in sync.

**Comment by georgantasp** [comment]
My pull request is actually an alternative solution to this as well:

https://github.com/mybatis/guice/pull/79

**Comment by christianpoitras** [comment]
@georgantasp Your solution is great too. I agree that both are equally useful.

**Comment by christianpoitras** [comment]
I think that after merging #79, this bug can be marked as fixed.
I will do this in the next few days.

**Comment by christianpoitras** [comment]
Fixed by merging #79

**Comment by george-hawkins-aa** [comment]
Sorry to followup so late on a long closed bug.

But was it the intention #79 to remove the ability to set properties like `"mybatis.configuration.defaultStatementTimeout"`?

See [here](https://github.com/mybatis/guice/commit/77091b8c09f9bb79fd2ba268d594b98c2a77855f#diff-d6155963f6d31d86f01669398a80ba43L95) in the #79 pull request to see where this and other `"mybatis.configuration"` prefixed properties were removed.

If you set this property now and then put a breakpoint in `BaseStatementHandler.setStatementTimeout(Statement, Integer)` I can see that nothing is picking up this property value anymore.

So it is not settable like so:

```Java
properties.put("mybatis.configuration.defaultStatementTimeout", "10");
Names.bindProperties(binder(), properties);
```

So at the moment I can only set it programmatically like so:

```java
MyBatisModule module = new MyBatisModule() {
    @Override
    protected void initialize() {
        // ...
        defaultStatementTimeout(5);
    }
};
```

On the whole #79 is very nice - I do like being able to access the `Configuration` instance directly in `initialize()` like so using Java 8 syntax:

    bindConfigurationSetting(configuration -> configuration.setDefaultStatementTimeout(10));

**Comment by christianpoitras** [comment]
It would be interesting to see if both can be used.
For that, bindConfigurationSetting would absolutely need to run after any properties are set.

I will test that this week.
