### ISSUE TITLE
datasource  hope to support druid

### ISSUE THREAD

**Issue by a598070240** [mybatis/guice#57]
with guice datasource,
hope add a java file  DruidDataSource
https://github.com/alibaba/druid

**Comment by christianpoitras** [comment]
I'm not really aware of the Druid data source.
If you are willing to program a DruidDataSourceProvider, I'll be happy to check it and add it to MyBatis-Guice.

You can look at the BasicDataSourceProvider to give you an idea of how to implement your own data source provider. https://github.com/mybatis/guice/blob/master/src/main/java/org/mybatis/guice/datasource/dbcp/BasicDataSourceProvider.java
In case, you don't know DBCP, there are several other providers under the datasource package.
https://github.com/mybatis/guice/tree/master/src/main/java/org/mybatis/guice/datasource

Thanks!

**Comment by lazeyliu** [comment]
well,I'm happy to provide the code ,e.. not git commit,


`import java.util.HashMap;
import java.util.Map;

import javax.sql.DataSource;

import com.alibaba.druid.pool.DruidDataSourceFactory;
import com.google.inject.Inject;
import com.google.inject.Provider;
import com.google.inject.name.Named;

/**
 * mybatis guice druid provider
 *
 * @author lazeyliu
 */
public class DruidDataSourceProvider implements Provider<DataSource> {

	Map<String, String>	config	= new HashMap<String, String>();

	@Inject
	public void setDriverClassName(@Named("JDBC.driverClassName") final String driverClassName) {
		config.put(DruidDataSourceFactory.PROP_DRIVERCLASSNAME, driverClassName);
	}

	@Inject
	public void setUrl(@Named("JDBC.url") final String url) {
		config.put(DruidDataSourceFactory.PROP_URL, url);
	}

	@Inject
	public void setUsername(@Named("JDBC.username") final String username) {
		config.put(DruidDataSourceFactory.PROP_USERNAME, username);
	}

	@Inject
	public void setPassword(@Named("JDBC.password") final String password) {
		config.put(DruidDataSourceFactory.PROP_PASSWORD, password);
	}

	@Inject(optional = true)
	public void setDefaultAutoCommit(@Named("JDBC.autoCommit") final String defaultAutoCommit) {
		config.put(DruidDataSourceFactory.PROP_DEFAULTAUTOCOMMIT, defaultAutoCommit);
	}

	@Inject(optional = true)
	public void setDefaultReadOnly(@Named("JDBC.readOnly") final String defaultReadOnly) {
		config.put(DruidDataSourceFactory.PROP_DEFAULTREADONLY, defaultReadOnly);
	}

	@Inject(optional = true)
	public void setDefaultTransactionIsolation(@Named("JDBC.transactionIsolation") final String defaultTransactionIsolation) {
		config.put(DruidDataSourceFactory.PROP_DEFAULTTRANSACTIONISOLATION, defaultTransactionIsolation);
	}

	@Inject(optional = true)
	public void setDefaultCatalog(@Named("JDBC.catalog") final String defaultCatalog) {
		config.put(DruidDataSourceFactory.PROP_DEFAULTCATALOG, defaultCatalog);
	}

	@Inject(optional = true)
	public void setMaxActive(@Named("JDBC.maxActive") final String maxActive) {
		config.put(DruidDataSourceFactory.PROP_MAXACTIVE, maxActive);
	}

	@Inject(optional = true)
	public void setMaxIdle(@Named("JDBC.maxIdle") final String maxIdle) {
		config.put(DruidDataSourceFactory.PROP_MAXIDLE, maxIdle);
	}

	@Inject(optional = true)
	public void setMinIdle(@Named("JDBC.minIdle") final String minIdle) {
		config.put(DruidDataSourceFactory.PROP_MINIDLE, minIdle);
	}

	@Inject(optional = true)
	public void setInitialSize(@Named("JDBC.initialSize") final String initialSize) {
		config.put(DruidDataSourceFactory.PROP_INITIALSIZE, initialSize);
	}

	@Inject(optional = true)
	public void setMaxWait(@Named("JDBC.maxWait") final String maxWait) {
		config.put(DruidDataSourceFactory.PROP_MAXWAIT, maxWait);
	}

	@Inject(optional = true)
	public void setTestOnBorrow(@Named("JDBC.testOnBorrow") final String testOnBorrow) {
		config.put(DruidDataSourceFactory.PROP_TESTONBORROW, testOnBorrow);
	}

	@Inject(optional = true)
	public void setTestOnReturn(@Named("JDBC.testOnReturn") final String testOnReturn) {
		config.put(DruidDataSourceFactory.PROP_TESTONRETURN, testOnReturn);
	}

	@Inject(optional = true)
	public void setTimeBetweenEvictionRunsMillis(@Named("JDBC.timeBetweenEvictionRunsMillis") final String timeBetweenEvictionRunsMillis) {
		config.put(DruidDataSourceFactory.PROP_TIMEBETWEENEVICTIONRUNSMILLIS, timeBetweenEvictionRunsMillis);
	}

	@Inject(optional = true)
	public void setNumTestsPerEvictionRun(@Named("JDBC.numTestsPerEvictionRun") final String numTestsPerEvictionRun) {
		config.put(DruidDataSourceFactory.PROP_NUMTESTSPEREVICTIONRUN, numTestsPerEvictionRun);
	}

	@Inject(optional = true)
	public void setMinEvictableIdleTimeMillis(@Named("JDBC.minEvictableIdleTimeMillis") final String minEvictableIdleTimeMillis) {
		config.put(DruidDataSourceFactory.PROP_MINEVICTABLEIDLETIMEMILLIS, minEvictableIdleTimeMillis);
	}

	@Inject(optional = true)
	public void setTestWhileIdle(@Named("JDBC.testWhileIdle") final String testWhileIdle) {
		config.put(DruidDataSourceFactory.PROP_TESTWHILEIDLE, testWhileIdle);
	}

	@Inject(optional = true)
	public void setValidationQuery(@Named("JDBC.validationQuery") final String validationQuery) {
		config.put(DruidDataSourceFactory.PROP_VALIDATIONQUERY, validationQuery);
	}

	@Inject(optional = true)
	public void setValidationQueryTimeout(@Named("JDBC.validationQueryTimeout") final String validationQueryTimeout) {
		config.put(DruidDataSourceFactory.PROP_VALIDATIONQUERY_TIMEOUT, validationQueryTimeout);
	}

	@Inject(optional = true)
	public void setInitConnectionSqls(@Named("JDBC.initConnectionSqls") final String initConnectionSqls) {
		config.put(DruidDataSourceFactory.PROP_INITCONNECTIONSQLS, initConnectionSqls);
	}

	@Inject(optional = true)
	public void setAccessToUnderlyingConnectionAllowed(@Named("JDBC.accessToUnderlyingConnectionAllowed") final String accessToUnderlyingConnectionAllowed) {
		config.put(DruidDataSourceFactory.PROP_ACCESSTOUNDERLYINGCONNECTIONALLOWED, accessToUnderlyingConnectionAllowed);
	}

	@Inject(optional = true)
	public void setRemoveAbandoned(@Named("JDBC.removeAbandoned") final String removeAbandoned) {
		config.put(DruidDataSourceFactory.PROP_REMOVEABANDONED, removeAbandoned);
	}

	@Inject(optional = true)
	public void setRemoveAbandonedTimeout(@Named("JDBC.removeAbandonedTimeout") final String removeAbandonedTimeout) {
		config.put(DruidDataSourceFactory.PROP_REMOVEABANDONEDTIMEOUT, removeAbandonedTimeout);
	}

	@Inject(optional = true)
	public void setlogAbandoned(@Named("JDBC.logAbandoned") final String logAbandoned) {
		config.put(DruidDataSourceFactory.PROP_LOGABANDONED, logAbandoned);
	}

	@Inject(optional = true)
	public void setPoolPreparedStatements(@Named("JDBC.poolPreparedStatements") final String poolPreparedStatements) {
		config.put(DruidDataSourceFactory.PROP_POOLPREPAREDSTATEMENTS, poolPreparedStatements);
	}

	@Inject(optional = true)
	public void setMaxOpenPreparedStatements(@Named("JDBC.maxOpenPreparedStatements") final String maxOpenPreparedStatements) {
		config.put(DruidDataSourceFactory.PROP_MAXOPENPREPAREDSTATEMENTS, maxOpenPreparedStatements);
	}

	@Inject(optional = true)
	public void setConnectionProperties(@Named("JDBC.connectionProperties") final String connectionProperties) {
		config.put(DruidDataSourceFactory.PROP_CONNECTIONPROPERTIES, connectionProperties);
	}

	@Inject(optional = true)
	public void setFilters(@Named("JDBC.filters") final String filters) {
		config.put(DruidDataSourceFactory.PROP_FILTERS, filters);
	}

	@Inject(optional = true)
	public void setExceptionSorter(@Named("JDBC.exceptionSorter") final String exceptionSorter) {
		config.put(DruidDataSourceFactory.PROP_EXCEPTION_SORTER, exceptionSorter);
	}

	@Inject(optional = true)
	public void setExceptionSorterClassName(@Named("JDBC.exception-sorter-class-name") final String exceptionSorterClassName) {
		config.put(DruidDataSourceFactory.PROP_EXCEPTION_SORTER, exceptionSorterClassName);
	}

	@Inject(optional = true)
	public void setInit(@Named("JDBC.init") final String init) {
		config.put(DruidDataSourceFactory.PROP_INIT, init);
	}

	@Override
	public DataSource get() {
		try {
			return DruidDataSourceFactory.createDataSource(config);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return null;
	}

}
`

**Comment by a598070240** [comment]
well,I'm happy to provide the code ,e.. not git commit,

`
import java.util.HashMap;
import java.util.Map;

import javax.sql.DataSource;

import com.alibaba.druid.pool.DruidDataSourceFactory;
import com.google.inject.Inject;
import com.google.inject.Provider;
import com.google.inject.name.Named;

/**

mybatis guice druid provider *
@author lazeyliu
*/
public class DruidDataSourceProvider implements Provider {

Map config = new HashMap();

@Inject
public void setDriverClassName(@Named("JDBC.driverClassName") final String driverClassName) {
config.put(DruidDataSourceFactory.PROP_DRIVERCLASSNAME, driverClassName);
}

@Inject
public void setUrl(@Named("JDBC.url") final String url) {
config.put(DruidDataSourceFactory.PROP_URL, url);
}

@Inject
public void setUsername(@Named("JDBC.username") final String username) {
config.put(DruidDataSourceFactory.PROP_USERNAME, username);
}

@Inject
public void setPassword(@Named("JDBC.password") final String password) {
config.put(DruidDataSourceFactory.PROP_PASSWORD, password);
}

@Inject(optional = true)
public void setDefaultAutoCommit(@Named("JDBC.autoCommit") final String defaultAutoCommit) {
config.put(DruidDataSourceFactory.PROP_DEFAULTAUTOCOMMIT, defaultAutoCommit);
}

@Inject(optional = true)
public void setDefaultReadOnly(@Named("JDBC.readOnly") final String defaultReadOnly) {
config.put(DruidDataSourceFactory.PROP_DEFAULTREADONLY, defaultReadOnly);
}

@Inject(optional = true)
public void setDefaultTransactionIsolation(@Named("JDBC.transactionIsolation") final String defaultTransactionIsolation) {
config.put(DruidDataSourceFactory.PROP_DEFAULTTRANSACTIONISOLATION, defaultTransactionIsolation);
}

@Inject(optional = true)
public void setDefaultCatalog(@Named("JDBC.catalog") final String defaultCatalog) {
config.put(DruidDataSourceFactory.PROP_DEFAULTCATALOG, defaultCatalog);
}

@Inject(optional = true)
public void setMaxActive(@Named("JDBC.maxActive") final String maxActive) {
config.put(DruidDataSourceFactory.PROP_MAXACTIVE, maxActive);
}

@Inject(optional = true)
public void setMaxIdle(@Named("JDBC.maxIdle") final String maxIdle) {
config.put(DruidDataSourceFactory.PROP_MAXIDLE, maxIdle);
}

@Inject(optional = true)
public void setMinIdle(@Named("JDBC.minIdle") final String minIdle) {
config.put(DruidDataSourceFactory.PROP_MINIDLE, minIdle);
}

@Inject(optional = true)
public void setInitialSize(@Named("JDBC.initialSize") final String initialSize) {
config.put(DruidDataSourceFactory.PROP_INITIALSIZE, initialSize);
}

@Inject(optional = true)
public void setMaxWait(@Named("JDBC.maxWait") final String maxWait) {
config.put(DruidDataSourceFactory.PROP_MAXWAIT, maxWait);
}

@Inject(optional = true)
public void setTestOnBorrow(@Named("JDBC.testOnBorrow") final String testOnBorrow) {
config.put(DruidDataSourceFactory.PROP_TESTONBORROW, testOnBorrow);
}

@Inject(optional = true)
public void setTestOnReturn(@Named("JDBC.testOnReturn") final String testOnReturn) {
config.put(DruidDataSourceFactory.PROP_TESTONRETURN, testOnReturn);
}

@Inject(optional = true)
public void setTimeBetweenEvictionRunsMillis(@Named("JDBC.timeBetweenEvictionRunsMillis") final String timeBetweenEvictionRunsMillis) {
config.put(DruidDataSourceFactory.PROP_TIMEBETWEENEVICTIONRUNSMILLIS, timeBetweenEvictionRunsMillis);
}

@Inject(optional = true)
public void setNumTestsPerEvictionRun(@Named("JDBC.numTestsPerEvictionRun") final String numTestsPerEvictionRun) {
config.put(DruidDataSourceFactory.PROP_NUMTESTSPEREVICTIONRUN, numTestsPerEvictionRun);
}

@Inject(optional = true)
public void setMinEvictableIdleTimeMillis(@Named("JDBC.minEvictableIdleTimeMillis") final String minEvictableIdleTimeMillis) {
config.put(DruidDataSourceFactory.PROP_MINEVICTABLEIDLETIMEMILLIS, minEvictableIdleTimeMillis);
}

@Inject(optional = true)
public void setTestWhileIdle(@Named("JDBC.testWhileIdle") final String testWhileIdle) {
config.put(DruidDataSourceFactory.PROP_TESTWHILEIDLE, testWhileIdle);
}

@Inject(optional = true)
public void setValidationQuery(@Named("JDBC.validationQuery") final String validationQuery) {
config.put(DruidDataSourceFactory.PROP_VALIDATIONQUERY, validationQuery);
}

@Inject(optional = true)
public void setValidationQueryTimeout(@Named("JDBC.validationQueryTimeout") final String validationQueryTimeout) {
config.put(DruidDataSourceFactory.PROP_VALIDATIONQUERY_TIMEOUT, validationQueryTimeout);
}

@Inject(optional = true)
public void setInitConnectionSqls(@Named("JDBC.initConnectionSqls") final String initConnectionSqls) {
config.put(DruidDataSourceFactory.PROP_INITCONNECTIONSQLS, initConnectionSqls);
}

@Inject(optional = true)
public void setAccessToUnderlyingConnectionAllowed(@Named("JDBC.accessToUnderlyingConnectionAllowed") final String accessToUnderlyingConnectionAllowed) {
config.put(DruidDataSourceFactory.PROP_ACCESSTOUNDERLYINGCONNECTIONALLOWED, accessToUnderlyingConnectionAllowed);
}

@Inject(optional = true)
public void setRemoveAbandoned(@Named("JDBC.removeAbandoned") final String removeAbandoned) {
config.put(DruidDataSourceFactory.PROP_REMOVEABANDONED, removeAbandoned);
}

@Inject(optional = true)
public void setRemoveAbandonedTimeout(@Named("JDBC.removeAbandonedTimeout") final String removeAbandonedTimeout) {
config.put(DruidDataSourceFactory.PROP_REMOVEABANDONEDTIMEOUT, removeAbandonedTimeout);
}

@Inject(optional = true)
public void setlogAbandoned(@Named("JDBC.logAbandoned") final String logAbandoned) {
config.put(DruidDataSourceFactory.PROP_LOGABANDONED, logAbandoned);
}

@Inject(optional = true)
public void setPoolPreparedStatements(@Named("JDBC.poolPreparedStatements") final String poolPreparedStatements) {
config.put(DruidDataSourceFactory.PROP_POOLPREPAREDSTATEMENTS, poolPreparedStatements);
}

@Inject(optional = true)
public void setMaxOpenPreparedStatements(@Named("JDBC.maxOpenPreparedStatements") final String maxOpenPreparedStatements) {
config.put(DruidDataSourceFactory.PROP_MAXOPENPREPAREDSTATEMENTS, maxOpenPreparedStatements);
}

@Inject(optional = true)
public void setConnectionProperties(@Named("JDBC.connectionProperties") final String connectionProperties) {
config.put(DruidDataSourceFactory.PROP_CONNECTIONPROPERTIES, connectionProperties);
}

@Inject(optional = true)
public void setFilters(@Named("JDBC.filters") final String filters) {
config.put(DruidDataSourceFactory.PROP_FILTERS, filters);
}

@Inject(optional = true)
public void setExceptionSorter(@Named("JDBC.exceptionSorter") final String exceptionSorter) {
config.put(DruidDataSourceFactory.PROP_EXCEPTION_SORTER, exceptionSorter);
}

@Inject(optional = true)
public void setExceptionSorterClassName(@Named("JDBC.exception-sorter-class-name") final String exceptionSorterClassName) {
config.put(DruidDataSourceFactory.PROP_EXCEPTION_SORTER, exceptionSorterClassName);
}

@Inject(optional = true)
public void setInit(@Named("JDBC.init") final String init) {
config.put(DruidDataSourceFactory.PROP_INIT, init);
}

@Override
public DataSource get() {
try {
return DruidDataSourceFactory.createDataSource(config);
} catch (Exception e) {
e.printStackTrace();
}
return null;
}

}

`

**Comment by christianpoitras** [comment]
It looks good at first sight. I will merge your pull request later.

**Comment by christianpoitras** [comment]
Fixed in commit e3ac1a8b1f8f9e1407c47844b4b58ef7b318655c.
