### ISSUE TITLE
Add support for `jakarta.*` namespace 

### ISSUE THREAD

**Issue by sgdesmet** [mybatis/guice#574]
Guice has recently released versions 6.0.0 (with partial jakarta namespace support) and 7.0.0 (without javax namespace support) (see their [documentation](https://github.com/google/guice/wiki/Guice600#jee-jakarta-transition).

Having jakarta namespace support in mybatis-guice would be convenient as well, as Tomcat 10 now only supports the new namespace, and many other libraries are migrating towards it.

**Comment by hazendaz** [comment]
Thanks for info.  Will try to get support going soon.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Stein Desmet ***@***.***>
Sent: Friday, July 14, 2023 4:09:43 AM
To: mybatis/guice ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mybatis/guice] Add support for `jakarta.*` namespace (Issue #574)


Guice has recently released versions 6.0.0 (with partial jakarta namespace support) and 7.0.0 (without javax namespace support) (see their documentation<https://github.com/google/guice/wiki/Guice600#jee-jakarta-transition>.

Having jakarta namespace support in mybatis-guice would be convenient as well, as Tomcat 10 now only supports the new namespace, and many other libraries are migrating towards it.

**Comment by sgdesmet** [comment]
I gave the upgrade a try, see my branch at https://github.com/sgdesmet/guice/tree/feat/guice7 
This appears to work with guice 7 and tomcat 10 in our project. 

This isn't complete yet though, as the mybatis-guice tests are broken because of the apache aries dependency which hasn't been migrated to jakarata. Maybe some rewriting will be needed, or a different transaction manager implementation which supports jakarta.

**Comment by christianpoitras** [comment]
Fixed by pull request #576.

**Comment by hazendaz** [comment]
That PR wasn't enough to be fully jakarta compatible.  While most was test related issues there was still javax usage on ejb and transaction in a few spots.  The libraries in the build had also grown substantially.  However, I was able to take care of all that and master currently is full on jakarta now.

@sgdesmet If you could give master a go and let me know if that works.  I'm working on a few other issues across all mybatis at the moment so its likely going to be about Tuesday or so before I release this.  If I don't hear anything back that is ok, will go forwards but would be great to know its in working order.  One change from earlier is that its java 11 or better now but that shouldn't be a problem considering you called out tomcat 10 usage and that in fact requires java 11 and the spec does as well even if not all modules actually did.

**Comment by sgdesmet** [comment]
@hazendaz ah looks like I missed a few things, apologies. I've tried out the master branch, everything appears to work as expected.

**Comment by hazendaz** [comment]
Thanks @sgdesmet for checking.  Glad to hear all good.  I'm still thinking tomorrow evening I release but waiting on maven so I can update a plugin for javadocs we have been having some troubles with.  They are voting and it should be out anytime. Once it is I plan to start releasing not only this but large portions of mybatis.  We had also just released the core which this also contains.   Again thanks for taking the time to double check here.

**Comment by hazendaz** [comment]
@sgdesmet Sorry for delays, this is now released.  Should be available in next 2 hours.
