### ISSUE TITLE
Specifying multiple independent JDBC URLs to try?

### ISSUE THREAD

**Issue by george-hawkins-aa** [mybatis/guice#62]
Currently I specify a single `JDBC.url` in the properties file I pass to:
```Java
Names.bindProperties(binder(), properties);
```

I know some DBs support specifying failovers in the JDBC URL itself. However we would like to specify multiple completely independent JDBC URLs for our read only datasource and then have MyBatis Guice try them in turn until it gets a valid connection.

Is this possible or is there a simple path to implementing it on top of the existing functionality?

**Comment by christianpoitras** [comment]
I don't think it is a feature that should be added to MyBatis-Guice since it seems to be related to specific datasources.

The way to go is to use a custom DataSource provider and set it in the MyBatisModule using bindDataSourceProvider() method.

**Comment by christianpoitras** [comment]
As for the question on how to set multiple URLs, you can implement it anyway you want in your provider. I would try first to set multiple values separated by commas or something alike.

https://commons.apache.org/proper/commons-configuration/userguide_v1.10/howto_properties.html#Properties_files

**Comment by george-hawkins-aa** [comment]
OK - thanks @christianpoitras - that seems a reasonable way to go.
