### ISSUE TITLE
Cannot handle multiple types with one generic type provider

### ISSUE THREAD

**Issue by kool79** [mybatis/guice#64]
Issue #30 add feature to define generic type providers, but it does not solve the problem - we can use such "generic" provider only once. (I.e. in code example we cannot use such type provider to bind to 2+ classes) For example, when we have provider
````java
class GenericCustomObjectTypeHandler<E extends CustomObject> extends BaseTypeHandler<E>
````
it can be used to handle  type *CustomObject*
````java
protected void initialize() {
  Class handlerClass = (Class)GenericCustomObjectTypeHandler.class;
  handleType(CustomObject.class).with(handlerClass);
}
````
But when we cannot  do this:
````java
protected void initialize() {
  Class handlerClass = (Class)GenericCustomObjectTypeHandler.class;
  handleType(CustomObjectA.class).with(handlerClass);
  handleType(CustomObjectB.class).with(handlerClass);
}
````
(both classes  CustomObjectA and CustomObjectB extends CustomObject)

To fix this injection of TypeLiteral for ObjectTypeHandler should be implemented to be able to call:
````java
protected void initialize() {
  handleType(CustomObjectA.class).with(new TypeLiteral<GenericCustomObjectTypeHandler<CustomObjectA>>() {});
  handleType(CustomObjectB.class).with(new TypeLiteral<GenericCustomObjectTypeHandler<CustomObjectB>>() {});
}
````

**Comment by christianpoitras** [comment]
Can you try commit 831648dbcedd93d0bbdf5318029b48ada239aeec and see if it works on your side too?

To use the same type handler for multiple types, you need to use TypeLiteral like in the MultipleGenericCustomObjectTypeHandlerTest class.
