### ISSUE TITLE
Guice throws CreationException when adding the same type handler in the Modules

### ISSUE THREAD

**Issue by georgantasp** [mybatis/guice#74]
As of the 3.7.0 version of mybatis-guice type handlers are bound using a provider instance instead of a provider class. This creates a subtle difference where type handlers cannot be added to multiple modules in the same injector.

The fix is super easy. Guice allows multiple bindings when the provided instances are equal. Can you please override equals (and hashCode) as you see fit for TypeHandlerProvider and possibly MapperProvider.

see https://github.com/TechniqueSoftware/clubos-mybatis-guice/commit/0d2c80b24fc7c0cd6b25d5a2e570bfaa3ee25b2f

Thanks

**Comment by christianpoitras** [comment]
I agree. But MyBatis supports Java 6 and Objects was introduced in Java 7. Can you fix this before I merge the code?

**Comment by georgantasp** [comment]
Hi Christian thanks for getting back.

I made the change to use google's Objects instead.

https://github.com/TechniqueSoftware/clubos-mybatis-guice/commit/6c8d09ab6249305510319dadccbc085d93619530

Do you have a more formal procedure for accepting contributions? I searched the docs pages but couldn't find anything. Just thought I'd ask because I have a few other enhancements I'm working on.

Thanks again.

**Comment by christianpoitras** [comment]
Usually people fork the project to their own account and make changes there. Then they submit a pull request. Once done, I can merge your code by clicking a single button!

That's the way to go for most projects in GitHub.
For example, this is my fork: https://github.com/christianpoitras/guice

**Comment by georgantasp** [comment]
https://github.com/mybatis/guice/pull/75

**Comment by christianpoitras** [comment]
Merged pull request #76
