### ISSUE TITLE
The program runs normally before packaging, but it encounters issues after packaging.

### ISSUE THREAD

**Issue by LetAmericaGreatAgain** [mybatis/guice#746]
![image](https://github.com/user-attachments/assets/2dbc5ae6-360b-470a-9632-327b825bfae9)
![image](https://github.com/user-attachments/assets/0f2cbffe-8f4d-4476-9824-3ce5d06204a8)

**Comment by hazendaz** [comment]
Closing as spam, this should have been on original ticket, its clear the issue here. I'm closing this here and will comment on the first.
