### ISSUE TITLE
How can this exception be resolved? It seems to be a bug in the framework itself.

### ISSUE THREAD

**Issue by LetAmericaGreatAgain** [mybatis/guice#747]
The program runs normally before packaging, but it encounters issues after packaging.You can reproduce this exception using the code from this Git repository: git@github.com:LetAmericaGreatAgain/ultimatesource-test.git

How can this exception be resolved? It seems to be a bug in the framework itself.

**Comment by hazendaz** [comment]
Please use your original ticket, do not open numerous for same issue, closing as spam.
