### ISSUE TITLE
I have identified a bug in this framework. When adding mapper-related classes or XML files using the package name, an exception occurs when running the application packaged as a JAR. Specifically, using the method addMapperClasses("com.test.mapper.mysql") causes an exception, but when using addMapperClass(ClassroomMapper.class), no exception occurs.

### ISSUE THREAD

**Issue by LetAmericaGreatAgain** [mybatis/guice#748]
![image](https://github.com/user-attachments/assets/2e2cfb3c-0144-4a18-9d46-c057f7e13c43)

**Comment by hazendaz** [comment]
Do not use intellij error reporter to open tickets.  You have effectively spammed us numerous tickets for one issue that isn't an issue with this framework.  Its an issue with your usage.  I'll explain on your first ticket.
