### ISSUE TITLE
Constructor Injection for TypeHandlers doesn't work.

### ISSUE THREAD

**Issue by georgantasp** [mybatis/guice#82]
I see that this is related to https://github.com/mybatis/guice/issues/30 .

When trying to upgrade to the latest version, that fix is breaking many of my typehandlers which need constructor injection.

As the original issue is described, I think the existing solution is too heavy handed. I'll propose a different solution shortly.

**Comment by christianpoitras** [comment]
The general problem comes from MyBatis-Guice trying to inject dependencies in type handlers. Removing that feature would fix the issue.
But if the injection feature is used, then we may end-up in a catch 22 situation...

**Comment by georgantasp** [comment]
https://github.com/mybatis/guice/pull/83

**Comment by georgantasp** [comment]
I think its better if this library gives the developer the option. I think adding more options to TypeHandlerBinder is the right way to go.

**Comment by christianpoitras** [comment]
Thanks. That's a nice addition!

Should I mark this as closed? Using Providers is a good alternative.

**Comment by georgantasp** [comment]
Marking closed for the purposes of this ticket.

Another future enhancement would be to expose a better syntax for the TypeHandlerBinder:

`handleType(type).byBinding(handlerType).to(handlerTypeProvider).in(Scopes.SINGLETON)`

**Comment by christianpoitras** [comment]
It looks like a better syntax. It may also be possible to handle generic handlers with this kind of syntax.
I don't use all the features of MyBatis, so I'm not up-to-date with all the recents improvements of the main framework. I'll have to dig into it! ;)
