### ISSUE TITLE
Cannot set configuration fields using properties

### ISSUE THREAD

**Issue by christianpoitras** [mybatis/guice#91]
Binding properties may not work anymore after fix #79.

```
properties.put("mybatis.configuration.defaultStatementTimeout", "10");
Names.bindProperties(binder(), properties);
```

Need to use this syntax now.
```
bindConfigurationSetting(configuration -> configuration.setDefaultStatementTimeout(10));
```

See issue #42.

**Comment by george-hawkins-aa** [comment]
For this particular property there is also a setter so you can do just plain:

    defaultStatementTimeout(10);

So this and setting the property directly on the configuration, i.e. `bindConfigurationSetting(configuration -> ...)`, work. But all the `"mybatis.configuration.XYZ"` properties that you used to be able to set via a (usually external) properties file seem to have been removed by #79.

**Comment by christianpoitras** [comment]
I restored this functionality. But no additional properties will be provided in the future.

**Comment by christianpoitras** [comment]
New configuration fields will only be settable using ConfigurationSettings.
I think it is an acceptable compromise.

**Comment by george-hawkins-aa** [comment]
Looks good 😄
