### ISSUE TITLE
Provide methods for settings logImpl, proxyFactory, jdbcTypeForNull, ...

### ISSUE THREAD

**Issue by xeredi** [mybatis/guice#93]
Hi. 

In Mybatis Guice, I found methods to initialize a MyBatisModule. For example:
- method "useCacheEnabled" for the setting "cacheEnabled"

But I can't find methods for settings:
- logImpl
- proxyFactory
- jdbcTypeForNull
- ...

Is there a way to modify this settings?

Thank you very much

**Comment by christianpoitras** [comment]
Please, ask your questions in the mailing list.
http://www.mybatis.org/mybatis-3/mail-lists.html

Look for `bindConfigurationSetting()` in the most recent version.
